version: "3"
services:
  # MongoDB for persistency
  mongo:
    image: mongo:3.6
    restart: on-failure

  # Restful backend API
  backend:
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/kidshub
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - .:/starter
      - /starter/node_modules
